name: Trigger Process Jobs

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call process_jobs endpoint
        run: |
          curl -X POST "https://kind-desert-0cf58b00f.1.azurestaticapps.net/api/process_jobs"
